### ISSUE TITLE
配送先登録/一覧画面について

### ISSUE THREAD

**Issue by cottoncandy31** [webcamp-team-c-shiba/naganocake-c-shiba#13]
https://i.gyazo.com/30f5bee5b4190a40c0add3ec9e5473e8.png

ブラウザ上で、配送先登録/一覧画面(末尾のURL：/addresses)を開こうとしたところ、AddressesControllerのindexアクション内でエラーが出ていました。
お手すきの際に、一度ご確認いただければと思います。

**Comment by banto354** [comment]
確認しました。
ログインしていない状態でもaddresses画面に入れる状態になっていたためにエラーが起きたのではないかと思います。
ログイン状態でのみアクセスできる制限に変えたbranchをプルリクエストするので、マージ後もエラー出るか確認お願いします!
