### ISSUE TITLE
管理者サインイン画面のエラー

### ISSUE THREAD

**Issue by banto354** [webcamp-team-c-shiba/naganocake-c-shiba#8]
![Screen Shot 2023-06-16 at 21 23 55](https://github.com/webcamp-team-c-shiba/naganocake-c-shiba/assets/35644224/e1c7290f-f468-4132-ab85-502a5184a981)

- 管理者用のログイン画面を開こうとしたところエラーが出ました。確認おねがいします!

**Comment by cottoncandy31** [comment]
修正点　下記2点
・ パラメーターの設定を削除しました
・ログイン/ログアウト後の遷移先(ルートパス)を修正しました
def after_sign_in_path_for(resource)
    admin_items_path
  end
 
  def after_sign_out_path_for(resource)
    new_admin_session_path
  end
