### ISSUE TITLE
管理者トップページのURL

### ISSUE THREAD

**Issue by JumpeiTo** [webcamp-team-c-shiba/naganocake-c-shiba#9]
https://gyazo.com/ffed9db1265e110bb0a00d9653ce9d0b

管理者トップページURLが設計書では/adminとなっているので修正が必要かと思います！
まだ途中やりでの事でしたらすみません。。。 @cottoncandy31

**Comment by banto354** [comment]
かくちゃんがプルリクしてコンフリクトした部分に関わっていた箇所だったので、コンフリクト修正の際にこちらも（勝手に）修正しました。ご確認お願いします! @cottoncandy31

**Comment by cottoncandy31** [comment]
上記について、確認いたしました！ありがとうございます。
